name: CI
on: 
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run npm ci
        run: npm ci
      - name: Check code format
        run: npm run format:check
      - name: Run tests
        run: npm test --coverange
        env:
          CI: true