name: CI
on: 
  pull_request:
    types: [reopened, edited, opened]
    branches: [dev]
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ci
        run: npm install
      - name: Check code format
        run: npm run lint
      - name: Run tests
        run: npm run test:cov
        env:
          CI: true
      - name: Build project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy to stagin
        if: github.event_name == 'push'
        env:
          DEPLOY_TOKEN: ${{secrets.DEPLOY_TOKEN}}
        run: "echo Your deploy stuff here ${DEPLOY_TOKEN}"
        
      
