name: CI
on: 
  pull_request:
    types: [reopened, edited]
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ci
        run: npm install
      - name: Check code format
        run: npm run lint
      - name: Run tests
        run: npm run test:cov
        env:
          CI: true